# Generated by Django 2.2.4 on 2020-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('time', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
            ],
        ),
    ]
