# Generated by Django 2.2.4 on 2020-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dramas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(default='')),
                ('time', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('poster', models.TextField(default='')),
                ('trailer_href', models.TextField(default='')),
                ('trailer_img', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer_href',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer_img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movies',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
